biomage-org/iac

.github/pull_request_template.md
README.md
cf/bioinformatics-access-group.yaml
cf/canaries.yaml
cf/cognito-case-insensitive.yaml
cf/developer-access-group.yaml
cf/irsa-api-role.yaml
cf/irsa-pipeline-role.yaml
cf/irsa-ui-role.yaml
cf/irsa-worker-role.yaml
cf/irsa-xray-daemon-role.yaml
cf/rds-agent-security-group.yaml
cf/rds-subnet-security-group.yaml
cf/rds.yaml
cf/redis.yaml
cf/s3-v2.yaml
cf/sns.yaml
cf/userpoolclient.yaml
charts/nodejs/values.yaml
infra/cf-iac-secret-key.yaml
infra/cf-state-machine-role.yaml
migrations/sql-migrations/README.md

To deploy to the staging environment, follow the instructions here: https://github.com/hms-dbmi-cellenics/biomage-utils

Set biomage-org references

---

.github/workflows/backup-cognito-users.yaml
.github/workflows/delete-unused-step-functions.yaml
.github/workflows/deploy-changed-cf.yaml
.github/workflows/deploy-changed-users.yaml
.github/workflows/deploy-infra.yaml
cf/canaries.yaml
cf/cognito-case-insensitive.yaml

remove the reference to HMS environment in the github workflows

---

cf/cognito-case-insensitive.yaml

Cloudformation fails because there is no sub in domain name

---

cf/bioinformatics-access-group.yaml

This is just a test to make sure that github reaches to AWS. I will revert it afterwards.

Test to verify that CF gets deployed in AWS

---

cf/bioinformatics-access-group.yaml

Revert "Test to verify that CF gets deployed in AWS"

---

cf/canaries.yaml

Add missing property

---

cf/bioinformatics-access-group.yaml
infra/aws-elb-503-subscription-endpoint/templates/ingress.yaml

Revert "removed bio group" because the changes weren't deployed

---

migrations/s3-migrations/add-dashes-to-experiment-id.py
migrations/s3-migrations/migrateToUniqueBuckets.sh

https://biomage.atlassian.net/browse/BIOMAGE-1952
https://github.com/biomage-org/api/pull/2
To deploy to the staging environment, follow the instructions here: https://github.com/hms-dbmi-cellenics/biomage-utils

1952 Add dashes to experiment id migration

---

cf/canaries.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2081

update node version on lambda functions

---

cf/doit-cloudhealth-role.yaml

Cloudformation for the role that doit use to display data in CloudHealth

---

infra/cluster-access/Biomage/cluster_admins_production
infra/cluster-access/HMS/cluster_admins_production
infra/cluster-access/trv/cluster_admins_production

add cluster access file for the new environment

---

.github/workflows/deploy-infra.yaml

remove trv

---

.github/workflows/deploy-infra.yaml

`account-config.yaml` path was moved. This PR corrects the reference to the newly moved path.

correct config file path

---

.github/workflows/deploy-infra.yaml
infra/config/github-environments-config.yaml
infra/datadog/cluster-agent-values.yaml

We need to install Datadog cluster agent to enable monitoring of cluster resources.
https://biomage.atlassian.net/browse/BIOMAGE-2152

[BIOMAGE-2152] - Add Datadog cluster agent

---

.github/workflows/deploy-monitoring.yaml

- Github will only show new workflow if the new workflow is merged with `master`.
- I want to test the content of the new workflow in #40 
- I created this PR to merge to `master` and enable the new workflow in Actions, so I can test the code in PR#40.
- The workflow in this PR contains dummy code. It'll be replaced by the code in #40 .
https://biomage.atlassian.net/browse/BIOMAGE-2153

[BIOMAGE-2153] - New workflow for deploying monitoring

---

.github/workflows/deploy-infra.yaml

Move to newer version of yq

---

migrations/sql-migrations/knexfile.js

Make sandbox_id check not throw for env development

---

.gitignore
cf/batch.yaml
cf/irsa-pipeline-role.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2189
https://ui-ahriman-api4-pipeline50.scp-staging.biomage.net/
https://github.com/biomage-org/api/pull/4
https://github.com/biomage-org/iac/pull/46
https://github.com/biomage-org/pipeline/pull/50

[BIOMAGE-2151] Added batch permissions & cf

---

cf/batch.yaml

added back dev as default

---

.github/workflows/deploy-changed-cf.yaml
.github/workflows/deploy-infra.yaml
infra/config/cluster/trv/cluster-admins-production

https://biomage.atlassian.net/browse/BIOMAGE-2142

[BIOMAGE-2142] Add biomage iam users to trv eks cluster

---

cf/batch.yaml
cf/irsa-api-role.yaml
infra/cf-state-machine-role.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2203

[BIOMAGE-2203] Parametrized subnets & security group in batch yaml

---

cf/batch.yaml

small typo in yaml

---

cf/batch.yaml
cf/irsa-pipeline-role.yaml

Firs tneeds to merge this PR https://github.com/biomage-org/iac/pull/56 because of this https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-computeenvironment.html#:~:text=When%20changing%20the%20value%20of%20this%20property%20to%20false%2C%20no%20other%20properties%20should%20be%20changed%20at%20the%20same%20time
https://biomage.atlassian.net/browse/BIOMAGE-2203
https://github.com/biomage-org/iac/pull/56
Is all relevant documentation updated to …

[2203] Add managed policy for aws batch

---

infra/code-private-endpoint-subscription-lambda.py

https://biomage.atlassian.net/browse/BIOMAGE-2142
N/A

[BIOMAGE-2142] Commit the code used for the lambda in trv deployment

---

cf/userpoolclient.yaml

localhost callback added

---

cf/developer-access-group.yaml

Need to add permissions for support cases
https://this-is-biomage.slack.com/archives/C0250TDU1PF/p1667554447847669?thread_ts=1667498040.100659&cid=C0250TDU1PF
N/A
N/A
N/A
N/A

Add support describe case attribues

---

infra/code-private-endpoint-subscription-lambda.py

Add missing headers on lambda function

---

.github/workflows/deploy-staging.yaml

Disable flux

---

cf/irsa-api-role.yaml

retriggering deploy cf

---

cf/irsa-pipeline-role.yaml

Trigger irs apipeline deploy

---

.github/workflows/deploy-infra.yaml

Remove flux from deploy infra

---

infra/code-private-endpoint-subscription-lambda.py

Persist code changes so that the Lambda that handles VPC networking can also handle k8s event.
https://biomage.atlassian.net/browse/BIOMAGE-2193
N/A
N/A
N/A

[BIOMAGE-2193] - VPC Lambda handle k8s event

---

charts/nodejs/templates/ingress.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2223
https://github.com/biomage-org/api/pull/42

[2223] Fix duplicate ingress

---

cf/developer-access-group.yaml

add batch view permissions

---

infra/code-private-endpoint-subscription-lambda.py

https://biomage.atlassian.net/browse/BIOMAGE-2241
https://github.com/biomage-org/pipeline/pull/63

[2241] send apiUrl in the sns message

---

.github/workflows/deploy-infra.yaml

Add the route53 records update section back

---

.github/workflows/deploy-infra.yaml
infra/config/account-config.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2290

[BIOMAGE-2290] - Add public facing in account-config

---

cf/irsa-api-role.yaml
cf/irsa-pipeline-role.yaml

[2251] Add permissions to run new pipeline type

---

.github/workflows/deploy-infra.yaml
charts/nodejs/templates/ingress.yaml
infra/aws-elb-503-subscription-endpoint/templates/ingress.yaml
infra/config/github-environments-config.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2290

[BIOMAGE-2290] - Add ingress scheme type

---

cf/irsa-pipeline-role.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2252

[2252] Add permissions for pipeline to get processed matrix

---

cf/irsa-pipeline-role.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2252

Add get cell sets permissions

---

.github/workflows/deploy-infra.yaml
README.md
cf/batch.yaml
charts/nodejs/templates/deployment.yaml
infra/config/account-config.yaml

Changes to support Batch monitoring:
- Datadog app key needs to be added to configmap so that it can be used in the API chart and passed down to the Batch job as environment variable. The app key is used by the Datadog library running in batch.
- Start script in the Batch job definition has to change
https://biomage.atlassian.net/browse/BIOMAGE-2264
IAC - https://github.com/biomage-org/iac/pull/92
API - https://github.com/biomage-org/api/pull/80
Pipeline - https://github.com/biomage-org/pipeline/pull/99
To deploy to the staging environment, follow the instructions here: …

[BIOMAGE-2264] - Add Batch monitoring

---

cf/developer-readonly-access-group.yaml

adding read only permissions to be able to give interns production access to for example download data with `biomage-utils`

created readonly permissions group

---

cf/irsa-event-exporter-role.yaml
charts/nodejs/templates/_helpers.tpl
charts/nodejs/templates/kubernetes-event-exporter.yaml

[BIOMAGE-2222] Event exporter configuration for cases when it goes through sns

---

infra/config/cluster/Biomage/cluster-admins-production
infra/config/cluster/Biomage/cluster-admins-staging

Remove Adam from cluster admins -- he never needed to access the cluster

---

.github/workflows/deploy-monitoring.yaml
infra/cluster-logging/node-fluentbit-config.yaml

Increase retention time for logs to 14 days

---

infra/cf-loadbalancer.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2368

[2368] Add drop invalid header fields

---

cf/sns.yaml

Enable SQS encryption at rest
Before encryption at rest is enabled:
What encryption at rest looks like if it is enabled:
Encryption at rest is enabled by default for SQS queues created after November 2021 (see [post](https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-sqs-announces-server-side-encryption-ssq-managed-sse-sqs-default/)).
This PR enables encryption for SQS queues.
https://biomage.atlassian.net/browse/BIOMAGE-2372
N/A
N/A
N/A
Is all relevant documentation …

[BIOMAGE-2372] - Enable sqs encryption at rest

---

infra/cf-loadbalancer.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2368

[2368] Enable deletion protection for lb

---

.github/workflows/deploy-infra.yaml
infra/cf-loadbalancer.yaml

Store ALB access logs in S3 bucket
Before
After
Log test file:
Added entry in the [new account Deployment Runbook](https://docs.google.com/document/d/1-283CcJ_vZdMLON0aEO0IFPEcuVarjUw3CFd6-DG3FQ/edit#) to remind people to check that the AWS ALB account id exists for the region the deployment is going to be made into.
https://biomage.atlassian.net/browse/BIOMAGE-2391
N/A 
N/A
N/A

[BIOMAGE-2391] - Enable ALB logs

---

cf/sns.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2350
N/A
this
N/A

[BIOMAGE-2350] - Remove SNS outputs

---

cf/irsa-api-role.yaml
cf/irsa-pipeline-role.yaml

Remove permissions to a bucket that doesn't exist

---

cf/irsa-api-role.yaml
cf/irsa-pipeline-role.yaml
cf/irsa-worker-role.yaml

More permissions to a bucket that doesn't exist

---

cf/irsa-api-role.yaml
cf/irsa-pipeline-role.yaml
cf/irsa-worker-role.yaml

Hopefully a last one. More useless permissions

---

cf/developer-access-group-rds.yaml

Delete most likely unused role for invoking the s3-delete-files lambda

---

cf/rds-subnet-security-group.yaml
cf/redis.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2366

[2366] Remove unused sharedNodeSecurityGroup

---

.github/workflows/migrate-database.yaml

Just register the new workflow so it'll be available in other branches. I'll open another branch and PR to do the real work.
https://biomage.atlassian.net/browse/BIOMAGE-2346
N/A
N/A
N/A

[BIOMAGE-2346] - Create new migration workflow

---

.github/workflows/deploy-staging.yaml
.github/workflows/remove-staging.yaml
cf/batch-job-definition.yaml
cf/batch.yaml
cf/irsa-event-exporter-role.yaml
cf/irsa-flux-image-reflector-role.yaml
cf/sns.yaml
cf/userpoolclient.yaml
infra/cf-state-machine-role.yaml

Add sandbox id to batch jobs, so staging environment with pipeline changes can use Batch.
Test:
**Environment with staged pipeline repo**
- New CloudFormation stack is created:
- Correct job definition is created, referring to the pipeline PR's image (PR 134) :  
- Staged an environment and ran batch:
**Environment without staged pipeline repo**
- New CloudFormation stack is created:
- Correct job definition is created, referring to the default image :
- Staged an environment and ran batch:
https://biomage.atlassian.net/browse/BIOMAGE-2328
N/A https://ui-agi-batch-jobdef.scp-staging.biomage.net/
IAC - https://github.com/biomage-org/iac/pull/139
API - https://github.com/biomage-org/api/pull/124
Utils - https://github.com/biomage-org/biomage-utils/pull/30
master
Your changes will be ready …

[BIOMAGE-2328] - Add sandbox id to batch jobdef

---

migrations/s3-migrations/remove-incorrectly-deleted-files.py

https://biomage.atlassian.net/browse/BIOMAGE-2083

Add script to delete files

---

cf/batch.yaml

increased available nodes to batch

---

cf/batch.yaml

change default machine to support 40GB pipelines in produciton

---

.github/workflows/deploy-infra.yaml

Fix deploy infra

---

migrations/config/bucketNames.js
migrations/sql-migrations/knexfile.js

Some migrations have dependencies. This PR adds them.
https://biomage.atlassian.net/browse/BIOMAGE-2345

[BIOMAGE-2345] - Add migration dependencies

---

.github/workflows/deploy-changed-cf.yaml
cf/ses.yaml

Create CF files for SNS domain validation so the API can send email notifications.
https://github.com/biomage-org/issues/issues/88
Email verification created:
Record set created:
N/A
N/A
IAC - https://github.com/biomage-org/iac/pull/162
API - https://github.com/biomage-org/api/pull/147
N/A

Add SES to verify email domain

---

.github/workflows/deploy-changed-cf.yaml

Add new input into changed CF workflow

Add input into changed CF workflow

---

cf/developer-access-group.yaml

Add permission to manage post-registration SNS subscription
N/A
N/A
N/A
N/A
N/A
N/A

Add permission to manage post-registration SNS subscription

---

cf/irsa-api-role.yaml
cf/irsa-pipeline-role.yaml

https://github.com/orgs/biomage-org/projects/2/views/1?pane=issue&itemId=28571163

[87] Add permissions for new copy pipeline

---

cf/irsa-api-role.yaml

[87] Fix permission granted to api for running copy pipeline

---

cf/s3-v2.yaml
infra/config/cluster/Biomage/cluster-admins-staging

S3 import retention

---

cf/s3-v2.yaml

S3 buckets - enable secure transport

---

.github/workflows/deploy-changed-cf.yaml
cf/irsa-api-role.yaml
cf/irsa-pipeline-role.yaml
cf/post-register-lambda.yaml
cf/s3-v2.yaml

Right now post-register-lambda uses SNS to hit the API endpoints which handle post-registration. This is causing problems in private deployments because the endpoints are not exposed to the internet. To resolve this we can make the lambda POST directly to the API. To do so we need : 
`API` - Remove SNS in the endpoint that handles post registration.
`Step 1` - Make lambda POST to API endpoint directly.
`Step 2` - Clean up SNS topic and subscription which is not used anymore.
https://github.com/biomage-org/issues/issues/92
N/A
API - https://github.com/biomage-org/api/pull/153
Step 1 - https://github.com/biomage-org/iac/pull/181
Step 1 - https://github.com/biomage-org/iac/pull/183
N/A
To set up easy …

Skip SNS in post-register-lambda

---

.github/workflows/load-config.yaml

Add load-config workflow

---

cf/delete-s3-file-lambda.yaml

https://github.com/orgs/biomage-org/projects/2/views/1?pane=issue&itemId=32051003
N/A
N/A
changes here
N/A
N/A

Add checks for file deletion lambda

---

.github/workflows/backup-cognito-users.yaml
.github/workflows/delete-unused-step-functions.yaml
.github/workflows/deploy-changed-users.yaml
.github/workflows/deploy-infra.yaml
.github/workflows/load-config.yaml

Fix hms merge

---

charts/nodejs/values.yaml

Remove unused reference to repo in values.yaml

---

cf/batch-job-definition.yaml
cf/canaries.yaml
cf/cognito-case-insensitive.yaml
cf/irsa-api-role.yaml
cf/sns.yaml

Fix hms merge: Trigger relevant cf files and remove unused values.yaml property

---

cf/batch-job-definition.yaml
cf/canaries.yaml
cf/cognito-case-insensitive.yaml
cf/irsa-api-role.yaml
cf/sns.yaml

Dummy changes

---

.github/workflows/deploy-changed-cf.yaml
cf/developer-access-group.yaml
cf/sns.yaml

Fix changed cf on merge

---

cf/batch-job-definition.yaml
cf/canaries.yaml
cf/cognito-case-insensitive.yaml
cf/irsa-api-role.yaml
cf/sns.yaml

Dummy changes to trigger ci

---

cf/ses.yaml

Pre-merge pending changes

---

.github/workflows/deploy-changed-users.yaml

Add temporary manual trigger for deploy-changed-users

---

.github/workflows/deploy-infra.yaml
.github/workflows/load-config.yaml

comment fixes
