- cf/canaries.yaml
To deploy to the staging environment, follow the instructions here: https://github.com/hms-dbmi-cellenics/biomage-utils
> Add expiration policy for the canary s3 bucket

- cf/irsa-api-role.yaml
- cf/irsa-pipeline-role.yaml
- cf/irsa-worker-role.yaml
added permissions to the api to clean the sources bucket. Now that we do the merge in QC, the old r.rds remains in the sources bucket and it's being picked up as an additional sample. Removed also unneeded permissions because the buckets are gone.
> added api permissions to remove sources bucket

- .github/workflows/deploy-infra.yaml
- infra/account-config.yaml
We need to add Datadog API key to config map so that it can be used by the pipeline and worker containers.
In this PR, I : 
- Added the API key into this repository's secret under the key `DATADOG_API_KEY`
- Updated the deploy-infra script to insert `DATADOG_API_KEY` into `myAccount.datadogApiKey`
https://biomage.atlassian.net/browse/BIOMAGE-2071
> Add datadog API key to configmap

- .github/workflows/backup-cognito-users.yaml
- .github/workflows/delete-unused-step-functions.yaml
- .github/workflows/deploy-changed-cf.yaml
- .github/workflows/deploy-infra.yaml
We are not notified of failing workflows anymore because we have not setup the bot token. This PR replaces the token with a new one. I've also inserted the bot token as a repository secret.
https://biomage.atlassian.net/browse/BIOMAGE-2103
> [BIOMAGE-2103] - Fix workflow failures notification

- .github/workflows/deploy-monitoring.yaml
- infra/cluster-logging/cf-cluster-log-cloudwatch-policy.yaml
- infra/cluster-logging/fargate-fluentbit-config.yaml
- infra/cluster-logging/node-fluentbit-config.yaml
- infra/cluster-logging/node-fluentbit-namespace.yaml
This PR installs FluentBit and corrresponding config into the cluster to forward API logs to Cloudwatch.
https://biomage.atlassian.net/browse/BIOMAGE-2154
> [BIOMAGE-2154] - Add cluster logging

- cf/batch.yaml
Being done alone beause of https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-computeenvironment.html#:~:text=When%20changing%20the%20value%20of%20this%20property%20to%20false%2C%20no%20other%20properties%20should%20be%20changed%20at%20the%20same%20time
https://biomage.atlassian.net/browse/BIOMAGE-2203
https://github.com/biomage-org/iac/pull/55
> Allow batch update without replacement

- charts/nodejs/values.yaml
- infra/aws-elb-503-subscription-endpoint/templates/ingress.yaml
https://biomage.atlassian.net/browse/BIOMAGE-2194
> [BIOMAGE-2194] Remove unneeded ingress annotations

- charts/nodejs/templates/ingress.yaml
Staging is broken because a required Kubernetes annotation is deleted from the ingress definition. This PR adds that annotation back.
> Insert `target-type: ip` annotation back into K8s

- infra/cluster-logging/node-fluentbit-config.yaml
I'm aggregating all the api pods logs into a single stream. I don't find any use case where one would like to see them separately. If we do find such a use case we can always make a log group of all of them (instead of just dumping them together into staging/production logs)
> Aggregating all api logs into a single stream

- cf/batch.yaml
I manually specify which instances we want because otherwise, when requesting 4 CPUs to be always available it would  use instance 2x`r6i.large` which as 2CPU & 16GB memory each. This is not desirable because for the time being we will be requesting 32GB for each pipeline until we fine-tune memory consumption. This means, that we would have 2 machines with 16GB and whenever a new pipeline arrives (requesting 32GB) it would need to spin up a new node `r6i.xlarge` (with 32GB of memory)
https://biomage.atlassian.net/browse/BIOMAGE-2218
To deploy to the staging environment, follow the …
> [BIOMAGE-2218] Select only r6i family instances

- .github/workflows/deploy-infra.yaml
When manually updating Route53 records in production, we didn't save the previous values of scp.biomage.net and *.scp.biomage.net As a result, when trying to apply the proper fix of production, we get the following error:
I will contact DoIt for help, but until then we should disable this step, or it will be failing all the time.
https://biomage.atlassian.net/browse/BIOMAGE-2291
> [BIOMAGE-2291] Disable route 53 step that is now going to be failing

- .github/workflows/deploy-infra.yaml
- infra/config/github-environments-config.yaml
Deploying Route 53 to the Flare deployment is still causing in an error. This blocks the completion of ticket [2290]((https://biomage.atlassian.net/browse/BIOMAGE-2290)). A separate [ticket 2314](https://biomage.atlassian.net/browse/BIOMAGE-2314) has been opened to address this issue.
For now, the required changes when configuring the cluster (adding `publicFacing` to the ConfigMap) will be done manually so that the rest of ticket 2290 (IAC PR #88) can be done.
https://biomage.atlassian.net/browse/BIOMAGE-2290
N/A
#88
N/A
N/A
To deploy to the staging environment, follow the instructions …
> [BIOMAGE-2290] - Comment out deploy route53 dns records

- .github/workflows/deploy-infra.yaml
- charts/nodejs/templates/deployment.yaml
- infra/config/account-config.yaml
- infra/config/github-environments-config.yaml
Adds a way to persist the option for NodeJS to allow connections to self-signed certificate endpoints.
https://biomage.atlassian.net/browse/BIOMAGE-2268
N/A
N/A
N/A
> [BIOMAGE-2268] - Add self-signed cert option

- .github/workflows/deploy-infra.yaml
- .github/workflows/deploy-monitoring.yaml
- infra/config/github-environments-config.yaml
**Tests:** 
1. Control works for all env names and types :
https://github.com/biomage-org/iac/actions/runs/3828323016
Setup logging and monitoring is run 3 times with the correct environment name, type and order (Biomage staging, Biomage production, trv production)
2. Deployment script runs:
https://github.com/biomage-org/iac/actions/runs/3828471669
4. Removing `monitoringEnabled` in `deploy-infra` works, correct metadata is created:
https://github.com/biomage-org/iac/actions/runs/3828390562
(Look at `Configure Kubernetes resrouces` > `Fill in account metadata`)
To deploy to the staging …
> Enable monitoring in other deployments

- cf/sns.yaml
Staging environment CF is failing, complaining that the export name exists. This happens because the exported name in staging enviroments do not contain sandbox id to make it unique.
https://biomage.atlassian.net/browse/BIOMAGE-2296
> [BIOMAGE-2296] - Add sandbox id to SNS export

- cf/rds-agent.yaml
https://biomage.atlassian.net/browse/BIOMAGE-2365
This replaces the current rds agents with new ones that have their root ebs volumes encrypted.
It was already ran for staging so it can be tried out.
Also going to ec2 in the aws console, looking at the rds agent for staging and clicking on the "storage" tab shows that the volume is encrypted now:
> [2365] Add encryption to root ebs volumes

- cf/irsa-api-role.yaml
> Remove api's capability to delete files from s3

- .github/workflows/deploy-infra.yaml
- cf/irsa-flux-image-reflector-role.yaml
- infra/flux/kustomization.yaml
Add IRSA role to allow image reflector controller to list images
Tested : 
- Created IRSA role:
- Ran configure cluster to test substitution of values for kustomization.yaml:
https://github.com/biomage-org/iac/actions/runs/4285255159
- Filled in kustomization.yaml and push to releases/deployment:
https://github.com/biomage-org/releases/commit/d97514d770722999b9df916d693e947a98bd2729
- Staged an environment and check are no errors in the `ImageRepository` and `ImagePolicy` resources for the environment:
- Confirmed changes to environment is propagated:
https://github.com/biomage-org/releases/commit/a2e05c52b0725896a907ee75906f62e6a5c965f5
https://biomage.atlassian.net/browse/BIOMAGE-2415
N/A
UI - https://github.com/biomage-org/ui/pull/191
API - https://github.com/biomage-org/api/pull/118 …
> [BIOMAGE-2415] - Add IRSA for flux image reflector

- cf/delete-s3-file-lambda.yaml
https://biomage.atlassian.net/browse/BIOMAGE-2083
N/A
In the case of nested files (as shown in the image in the issue) the `delete-s3-file-lambda` recieves the folder that the objects are stored in as a key for the `DELETE` request. The files inside of the folder are never marked for deletion, thus their latest version remains the same and their lifecycle does not start elapsing.
The PR gets all the files that are prefixed with the folder name and sends a delete request for each of them. The latest version of each file is now the Delete Marker and their lifecycle starts.
_Note: Folders in S3 do not exist in the general sense, but they are just prefixes to files. S3 creates a 0-byte file with the same name as prefix to simulate a folder (this is how it handles empty folders). The reason …
> Make deletion lambda take into account nested files

- infra/config/cluster/cluster-template.yaml
- infra/config/cluster/trv/custom-cluster-config.yaml
https://biomage.atlassian.net/browse/BIOMAGE-2044
https://biomage.atlassian.net/browse/BIOMAGE-2365
> [2356] [2044] Remove v2 nodegroup

- .github/workflows/deploy-infra.yaml
- infra/config/cluster/cluster-template.yaml
deploy-infra action last run: https://github.com/biomage-org/iac/actions/runs/4566944269
This is currently active in staging, and it seems to be working fine.
https://biomage.atlassian.net/browse/BIOMAGE-2414
> [2414] Fix deploy infra with create cluster

- .github/workflows/deploy-infra.yaml
Based on the response to this https://github.com/fluxcd/flux2/discussions/3679 I'm adding version pinning for the flux cli using the format mentioned [here](https://github.com/fluxcd/flux2/discussions/489#discussioncomment-3858081).
N/A
> Pin flux cli version

- infra/cf-github-oidc.yaml
Needs to increase OIDC maximum session duration from 60 min to 2 hours, because configure cluster may take about an hour to complete.
> add max session duration

- infra/config/cluster/cluster-template.yaml
There was a missing `type` in the cluster configuration so the scale down jobs for `pipeline-default` and `worker-default` were running in fargate incurring into extra costs.
> running scale down out of fargate for default profiles

- .github/workflows/deploy-changed-cf.yaml
This was mistakenly removed by PR. The `if` statement checks whether we have to run setup RDS roles.
N/A
N/A
https://github.com/biomage-org/iac/pull/163
N/A
> readd setup rds roles check

- infra/cf-github-oidc.yaml
The previous thumbprint that Github was using is expired (see https://github.com/aws-actions/configure-aws-credentials/issues/357#issuecomment-1610927373). There's a new thumbprint that needs to be added (see https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/)
https://github.com/biomage-org/iac/actions/runs/5411277337/jobs/9833813781
N/A
N/A
N/A
> Add new Github OIDC thumbprint
